function initializeBusses
% This function initializes the busses 

%% Create the plant feedback bus automatically
busElementData = {...
    'gammaWing',1;...
    'gammaRudder',1;...
    'positionGFS',3;...
    'heading',1;...
    'headingDot',1;...
    'BFXDot',1;...
    'vAppWindGFC',3;...
    'MzBFC',1;...
    };
createBusInBaseWorkspace(busElementData,'busPlantFeedback')

%% Create the controller feedback bus automatically
busElementData = {...
    'basisParams',2;...
    'performanceIndex',1;...
    'energyGenerationTerm',1;...
    'spatialErrorTerm',1;...
    };
createBusInBaseWorkspace(busElementData,'busControllerFeedback')

%% Create the controller output bus automatically
clear busElementData
busElementData = {'wingAngleCommand',1;...
    'rudderAngleCommand',1};
createBusInBaseWorkspace(busElementData,'busControllerOutput')



end