function initializeBusses
% This function initializes the busses 

%% Create the plant output bus automatically
busElementData = {...
    'gammaWing',1;...
    'gammaRudder',1;...
    'positionGFS',3;...
    'psi',1;...
    'psiDot',1;...
    'velocityBFX',1;...
    'vAppWindGFC',3;...
    'MzBFC',1;...
    };
createBusInBaseWorkspace(busElementData,'busPlantFeedback')

%% Create the controller output bus automatically
clear busElementData
busElementData = {'wingAngleCommand',1;...
    'rudderAngleCommand',1};
createBusInBaseWorkspace(busElementData,'busControllerOutput')

end