yLimits = get(gca,'YLim');
line((p.numInitializationLaps+0.5)*[1 1],yLimits,...
    'Color','k','LineWidth',2)

text(p.numInitializationLaps-0.5,yLimits(1)+0.3*(yLimits(2)-yLimits(1)),...
    '$\uparrow$ Initialization $\uparrow$','FontSize',16,...
    'Rotation',90)

text(p.numInitializationLaps+2,yLimits(1)+0.9*(yLimits(2)-yLimits(1)),...
    '$\uparrow$Optimization$\uparrow$','FontSize',16,'Rotation',-90)
